apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - cm.yaml
  - deploy.yaml
  - svc.yaml
images:
  - name: quarkus
    newName: nginx:latest
    newTag: 0.0.0
